### ISSUE TITLE
Have "Select/Deselect all" all on the section selection page

### ISSUE THREAD

**Issue by j-wing** [lambdaloop/cal-schedule#3]
I often have already chosen a section for at least one class by the time I use the scheduling tool. If that class has a large number of sections, I have to individually deselect each one except LEC and the section I want. It would be useful to instead be able to hit a button to deselect all of them, and then select only the ones I want. 

Edit: just saw that you welcome PRs - I'll go ahead and take a stab it this myself, if you don't mind. :)

**Comment by lambdaloop** [comment]
Yeah, I don't know if I was dreaming or something, but I thought I implemented this feature. Upon looking through my code, I did not. 

A PR would be awesome! The relevant files are class_details.jsx (has the frontend for the sections side view, where you can add the buttons), and reducers.js (has the actions for redux, where you can add an action for deselecting and selecting all the sections).
